import type { Metadata } from 'next'
import React, { Suspense } from 'react';
const Navbar = React.lazy(() => import('../components/Navbar'));
// These styles apply to every route in the application
import './globals.css'
import Featuredcourses from '../components/Featuredcourses';
  // import Navbar from '../components/Navbar';
  

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return ( 
    <html lang="en" className="dark">
      <body>
         
     {children}
        <div className='relative w-full flex items-center justify-center'>
           <Navbar/>
  </div>
           </body>
	 
    </html>
  )
}
